name: kernel-images

on:
  push:
    tags:
      - "*"
jobs:
  kernel-ROOT:
    runs-on: ubuntu-latest
    env:
        working-director: /code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - uses: cvmfs-contrib/github-action-cvmfs@v4
      - name: Take lib files from CVMFS
        run: |
          mkdir xrdfs_locallib
          cd xrdfs_locallib
          rsync -ar --exclude 'python3.9' --exclude 'libROO*' --exclude 'libRoo*' /cvmfs/sft.cern.ch/lcg/views/LCG_103/x86_64-ubuntu2004-gcc9-opt/lib ./
          cd ..
      - name: Build container kernel-ROOT
        uses: docker/build-push-action@v2
        with:
          context: ./kernel-ROOT/
          outputs: "type=registry,push=true"
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/kernel-ROOT:${{ env.RELEASE_VERSION }}
          file: ./kernel-ROOT/Dockerfile
          platforms: linux/amd64
  kernel-Coffea:
    runs-on: ubuntu-latest
    env:
        working-director: /code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - uses: cvmfs-contrib/github-action-cvmfs@v4
      - name: Take lib files from CVMFS
        run: |
          mkdir xrdfs_locallib
          cd xrdfs_locallib
          rsync -ar --exclude 'python3.9' --exclude 'libROO*' --exclude 'libRoo*' /cvmfs/sft.cern.ch/lcg/views/LCG_103/x86_64-ubuntu2004-gcc9-opt/lib ./
          cd ..
      - name: Build container kernel-Coffea
        uses: docker/build-push-action@v2
        with:
          context: ./kernel-Coffea/
          outputs: "type=registry,push=true"
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/kernel-Coffea:${{ env.RELEASE_VERSION }}
          file: ./kernel-Coffea/Dockerfile
          platforms: linux/amd64
  kernel-mkShapesRDF:
    needs: kernel-ROOT
    runs-on: ubuntu-latest
    env:
        working-director: /code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - uses: cvmfs-contrib/github-action-cvmfs@v4
      - name: Take lib files from CVMFS
        run: |
          mkdir xrdfs_locallib
          cd xrdfs_locallib
          rsync -ar --exclude 'python3.9' --exclude 'libROO*' --exclude 'libRoo*' /cvmfs/sft.cern.ch/lcg/views/LCG_103/x86_64-ubuntu2004-gcc9-opt/lib ./
          cd ..
      - name: Build container kernel-mkShapesRDF
        uses: docker/build-push-action@v2
        with:
          context: ./kernel-mkShapesRDF/
          outputs: "type=registry,push=true"
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/kernel-mkshapesrdf:${{ env.RELEASE_VERSION }}
          file: ./kernel-mkShapesRDF/Dockerfile
          platforms: linux/amd64
  kernel-PocketCoffea:
    needs: kernel-Coffea
    runs-on: ubuntu-latest
    env:
        working-director: /code
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - uses: cvmfs-contrib/github-action-cvmfs@v4
      - name: Take lib files from CVMFS
        run: |
          mkdir xrdfs_locallib
          cd xrdfs_locallib
          rsync -ar --exclude 'python3.9' --exclude 'libROO*' --exclude 'libRoo*' /cvmfs/sft.cern.ch/lcg/views/LCG_103/x86_64-ubuntu2004-gcc9-opt/lib ./
          cd ..
      - name: Build container kernel-PocketCoffea
        uses: docker/build-push-action@v2
        with:
          context: ./kernel-PocketCoffea/
          outputs: "type=registry,push=true"
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/kernel-PocketCoffea:${{ env.RELEASE_VERSION }}
          file: ./kernel-PocketCoffea/Dockerfile
          platforms: linux/amd64
